wait for checks to finish

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -53,5 +53,12 @@ jobs:
             - name: Docker ${{ matrix.name }}
               run: sudo chmod -R 777 tests/e2e/${{ matrix.name }}/nodes && cd tests/e2e/${{ matrix.name }} && docker-compose up # -d
 
-            - name: Test ${{ matrix.name }}
-              run: echo 1
+            - name: Running checks for ${{ matrix.name }}
+              run: |
+                container_id=$(docker ps -a | grep 'consensus_checks' | awk '{print $1}')
+                while docker ps | grep -q $container_id; do echo "checks running..."; sleep 2; done
+                exit_code=$(docker container inspect $container_id --format='{{.State.ExitCode}}')
+                if [ "$exit_code" != "0" ]; then
+                  echo "Error: checks exited with code $exit_code"
+                  exit 1
+                fi
